stages:
    - build
    - push

build_image:
  stage: build
  script:
    - ls -la
    - npm install --registry=https://registry.npm.taobao.org
    - npm run build
    - CI_COMMIT_TAG=`git log | grep -e "^commit.*" | wc -l` && docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" .
  only:
    - master
  tags:
    - etAppV2


push_image:
  stage: push
  script:
    - pwd
    - set -xe
    - CI_COMMIT_TAG=`git log | grep -e "^commit.*" | wc -l` && docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" && docker rmi "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
  only:
    - master
  tags:
    - etAppV2
